# Generated by Django 3.2.12 on 2022-10-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subway', models.PositiveIntegerField()),
                ('bus', models.PositiveIntegerField()),
                ('book', models.PositiveIntegerField()),
                ('golf', models.PositiveIntegerField()),
                ('bath', models.PositiveIntegerField()),
                ('gas', models.PositiveIntegerField()),
                ('laundry', models.PositiveIntegerField()),
                ('movie', models.PositiveIntegerField()),
                ('bakery', models.PositiveIntegerField()),
                ('gym', models.PositiveIntegerField()),
                ('hospital', models.PositiveIntegerField()),
                ('pharmacy', models.PositiveIntegerField()),
                ('medical', models.PositiveIntegerField()),
                ('safefy', models.PositiveIntegerField()),
                ('police', models.PositiveIntegerField()),
                ('fire', models.PositiveIntegerField()),
                ('park', models.PositiveIntegerField()),
                ('karaoke', models.PositiveIntegerField()),
                ('billiard', models.PositiveIntegerField()),
                ('restaurant', models.PositiveIntegerField()),
                ('mart', models.PositiveIntegerField()),
                ('shop', models.PositiveIntegerField()),
            ],
        ),
    ]
