# Generated by Django 3.2.12 on 2022-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('traffic', models.PositiveIntegerField()),
                ('subway', models.PositiveIntegerField()),
                ('bus', models.PositiveIntegerField()),
                ('treatment', models.PositiveIntegerField()),
                ('hospital', models.PositiveIntegerField()),
                ('pharmacy', models.PositiveIntegerField()),
                ('medical', models.PositiveIntegerField()),
                ('welfare', models.PositiveIntegerField()),
                ('security', models.PositiveIntegerField()),
                ('police', models.PositiveIntegerField()),
                ('fire', models.PositiveIntegerField()),
                ('post', models.PositiveIntegerField()),
                ('library', models.PositiveIntegerField()),
                ('facilities', models.PositiveIntegerField()),
                ('bath', models.PositiveIntegerField()),
                ('laundry', models.PositiveIntegerField()),
                ('leisure', models.PositiveIntegerField()),
                ('park', models.PositiveIntegerField()),
                ('museum', models.PositiveIntegerField()),
                ('golf', models.PositiveIntegerField()),
                ('gym', models.PositiveIntegerField()),
                ('billard', models.PositiveIntegerField()),
                ('karaoke', models.PositiveIntegerField()),
                ('movie', models.PositiveIntegerField()),
                ('shop', models.PositiveIntegerField()),
                ('department', models.PositiveIntegerField()),
                ('complex', models.PositiveIntegerField()),
                ('center', models.PositiveIntegerField()),
                ('book', models.PositiveIntegerField()),
                ('mart', models.PositiveIntegerField()),
                ('large', models.PositiveIntegerField()),
                ('none', models.PositiveIntegerField()),
                ('supermarket', models.PositiveIntegerField()),
                ('market', models.PositiveIntegerField()),
                ('bakery', models.PositiveIntegerField()),
                ('restaurant', models.PositiveIntegerField()),
                ('west', models.PositiveIntegerField()),
                ('bunsik', models.PositiveIntegerField()),
                ('japan', models.PositiveIntegerField()),
                ('china', models.PositiveIntegerField()),
                ('korea', models.PositiveIntegerField()),
                ('cafe', models.PositiveIntegerField()),
                ('fast', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mamul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.PositiveIntegerField()),
                ('unnamed', models.PositiveIntegerField()),
                ('predict', models.FloatField()),
                ('jachigu', models.CharField(max_length=50)),
                ('bubjung', models.CharField(max_length=50)),
                ('height', models.PositiveIntegerField()),
                ('junwallse', models.CharField(max_length=50)),
                ('pyeong', models.FloatField()),
                ('bozeonggum', models.PositiveIntegerField()),
                ('imdaeru', models.PositiveIntegerField()),
                ('gunmullmyeong', models.CharField(max_length=50)),
                ('gunchukyear', models.PositiveIntegerField()),
                ('gunmulyongdo', models.CharField(max_length=50)),
                ('lastbozeong', models.PositiveIntegerField()),
                ('lastimdaeru', models.PositiveIntegerField()),
                ('zibunjuso', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
