# Generated by Django 3.2.12 on 2022-10-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jachibubjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jachigu', models.CharField(max_length=50)),
                ('bubjung', models.CharField(max_length=50)),
            ],
        ),
    ]
