# Generated by Django 3.2.12 on 2022-10-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mamul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.PositiveIntegerField()),
                ('predict', models.FloatField()),
                ('jachigu', models.CharField(max_length=50)),
                ('bubjung', models.CharField(max_length=50)),
                ('height', models.PositiveIntegerField()),
                ('junwallse', models.CharField(max_length=50)),
                ('pyeong', models.FloatField()),
                ('bozeonggum', models.PositiveIntegerField()),
                ('imdaeru', models.PositiveIntegerField()),
                ('gunmullmyeong', models.CharField(max_length=50)),
                ('gunchukyear', models.PositiveIntegerField()),
                ('gunmulyongdo', models.CharField(max_length=50)),
                ('lastbozeong', models.PositiveIntegerField()),
                ('lastimdaeru', models.PositiveIntegerField()),
                ('zibunjuso', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
