# Generated by Django 3.2.12 on 2022-10-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=10)),
                ('predict', models.TextField()),
                ('jachigu', models.CharField(max_length=10)),
                ('bubjung', models.CharField(max_length=10)),
                ('height', models.TextField()),
                ('junwallse', models.CharField(max_length=10)),
                ('pyeong', models.TextField()),
                ('bozeonggum', models.TextField()),
                ('imdaeru', models.TextField()),
                ('gunmullmyeong', models.CharField(max_length=10)),
                ('lastbozeong', models.TextField()),
                ('lastimdaeru', models.TextField()),
                ('zibunjuso', models.CharField(max_length=30)),
                ('X', models.TextField()),
                ('Y', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
