# Generated by Django 3.2.12 on 2022-10-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_database'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='X',
            new_name='gunchukyear',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='Y',
            new_name='gunmulyongdo',
        ),
        migrations.AlterField(
            model_name='database',
            name='lastbozeong',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='database',
            name='zibunjuso',
            field=models.TextField(),
        ),
    ]
