# Generated by Django 3.2.12 on 2022-10-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_mamul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='id',
        ),
        migrations.AlterField(
            model_name='facilities',
            name='title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
