# Generated by Django 3.2.12 on 2022-10-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_jachibubjung_xy'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_num', models.PositiveIntegerField()),
                ('dong', models.CharField(max_length=50)),
            ],
        ),
    ]
