# Generated by Django 3.2.12 on 2022-10-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
