# Generated by Django 3.2.12 on 2022-10-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_auto_20221019_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='c',
            new_name='zibunjuso',
        ),
    ]
