# Generated by Django 3.2.12 on 2022-10-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0009_auto_20221019_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='c',
            field=models.TextField(),
        ),
    ]
