# Generated by Django 3.2.12 on 2022-10-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0010_alter_database_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='a',
            new_name='gunchukyear',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='b',
            new_name='gunmulyongdo',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='c',
            new_name='lastbozeong',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='d',
            new_name='lastimdaeru',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='e',
            new_name='zibunjuso',
        ),
    ]
