# Generated by Django 3.2.12 on 2022-10-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0011_auto_20221019_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='lastimdaeru',
            new_name='a',
        ),
    ]
