# Generated by Django 3.2.12 on 2022-10-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0012_rename_lastimdaeru_database_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='a',
            new_name='yongdo',
        ),
    ]
