# Generated by Django 3.2.12 on 2022-10-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0013_rename_a_database_yongdo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='lastbozeong',
            new_name='year',
        ),
    ]
