# Generated by Django 3.2.12 on 2022-10-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0014_rename_lastbozeong_database_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='gunchukyear',
        ),
    ]
